# Generated by Django 5.2.4 on 2025-10-10 09:37

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mobile', 'Mobile'), ('LED/OLED TV', 'LED/OLED TV'), ('Computer Hardware', 'Computer Hardware'), ('Soundbar', 'Soundbar'), ('Speaker', 'Speaker'), ('Laptop', 'Laptop'), ('Projector', 'Projector'), ('Headphones', 'Headphones'), ('Camera', 'Camera'), ('Smartwatch', 'Smartwatch'), ('Gaming', 'Gaming'), ('WiFi Router', 'WiFi Router'), ('Smart Home Device', 'Smart Home Device')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('section', models.CharField(choices=[('latest', 'Latest Launches'), ('deals', 'Best Deals'), ('other', 'Other')], default='other', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('internal_storage', models.CharField(blank=True, max_length=50, null=True)),
                ('battery', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_camera', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_camera', models.CharField(blank=True, max_length=50, null=True)),
                ('processor', models.CharField(blank=True, max_length=255, null=True)),
                ('ram_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_type', models.CharField(blank=True, max_length=50, null=True)),
                ('processor_generation', models.CharField(blank=True, max_length=50, null=True)),
                ('ssd_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('touch_screen', models.CharField(blank=True, max_length=10, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('tv_operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('smart_features', models.CharField(blank=True, max_length=255, null=True)),
                ('usb_ports', models.IntegerField(blank=True, null=True)),
                ('hdmi_ports', models.IntegerField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('refresh_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('display_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tv_screen_size', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('wired_wireless', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compatible_with', models.CharField(blank=True, max_length=200, null=True)),
                ('felt_timer', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('mega_pixel', models.CharField(blank=True, max_length=20, null=True)),
                ('camera_color', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sensor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('dial_shape', models.CharField(blank=True, choices=[('Contemporary', 'Contemporary'), ('Curved', 'Curved'), ('Oval', 'Oval'), ('Rectangle', 'Rectangle'), ('Round', 'Round'), ('Square', 'Square'), ('Tonneau', 'Tonneau')], max_length=20, null=True)),
                ('display_size', models.CharField(blank=True, max_length=50, null=True)),
                ('ideal_for', models.CharField(blank=True, choices=[('Kids', 'Kids'), ('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], max_length=20, null=True)),
                ('wireless_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('colors', models.ManyToManyField(blank=True, to='core.color')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_details/')),
                ('colors', models.ManyToManyField(blank=True, to='core.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productname')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('alt_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('is_delivery', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('quantity', models.IntegerField()),
                ('colors', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_products/')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('full_details', models.JSONField(blank=True, default=dict)),
                ('latest_launch', models.BooleanField(default=False)),
                ('best_deal', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brandname')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productname')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.FloatField()),
                ('payment_method', models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Card'), ('emi', 'EMI'), ('netbanking', 'Net Banking'), ('cod', 'Cash on Delivery')], max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('order_confirmed', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shippingaddress')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('selected_color', models.CharField(blank=True, max_length=50, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
