# Generated by Django 5.2.4 on 2025-10-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shopproduct_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_products/')),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.shopproduct')),
            ],
        ),
    ]
