# Generated by Django 5.2.4 on 2025-10-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shopproductimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopProductImage',
        ),
    ]
