# Generated by Django 5.2.4 on 2025-10-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_shopproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='show_in_shop',
            field=models.BooleanField(default=True),
        ),
    ]
