# Generated by Django 5.2.4 on 2025-10-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shopproduct_show_in_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='is_home_similar',
            field=models.BooleanField(default=False),
        ),
    ]
