# Generated by Django 5.2.4 on 2025-10-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shopproduct_is_home_similar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
