# Generated by Django 5.2.4 on 2025-10-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_stock_reduced'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
