# Generated by Django 5.2.4 on 2025-10-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shopproduct_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_product/descriptions/'),
        ),
    ]
