# Generated by Django 5.2.4 on 2025-10-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_shopproduct_text_shopproduct_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='text',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='descriptions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_products/'),
        ),
    ]
