# Generated by Django 5.2.4 on 2025-10-16 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_shopproduct_text_shopproduct_descriptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='title',
        ),
        migrations.CreateModel(
            name='ShopProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_product/descriptions/')),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='core.shopproduct')),
            ],
        ),
    ]
