# Generated by Django 5.2.4 on 2025-10-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_shopproduct_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
